#!/bin/bash
set -e

case "$1" in
    purge)
       find /apps/utserver/* -maxdepth 0 -type 'f' | grep -v "app-config" | xargs rm -f
       find /apps/utserver/* -maxdepth 0 -type 'd' | grep -v "app-config" | xargs rm -rf

       if [ -f /apps/utserver/.localapp ]; then
         rm /apps/utserver/.localapp
       fi

       ;;
    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
       ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 0

esac
